{
    "list":[{
        'materialName':'生抽',
        'materialList':[{
            'material':'生抽',
            'disheName':'家常韭菜饼',
            'dosage':'1勺子'},
            {
                'material':'生抽',
                'disheName':'啤酒烤鸭',
                'dosage':'2勺子'},
                ,
            {
                'material':'生抽',
                'disheName':'炒鸡蛋',
                'dosage':'0.5勺子'},
        ]
        
    },{
        'materialName':'面粉',
        'materialList':[{
            'material':'面粉',
            'disheName':'家常韭菜饼',
            'dosage':'1勺子'},
            {
                'material':'面粉',
                'disheName':'啤酒烤鸭',
                'dosage':'2勺子'},
                ,
            {
                'material':'面粉',
                'disheName':'炒鸡蛋',
                'dosage':'0.5勺子'},
        ]
        
    },]
}